<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
	  <TargetFramework>net9.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CS8602;CS8604</NoWarn>
  </PropertyGroup>

  <ItemGroup>
	  <FrameworkReference Include="Microsoft.AspNetCore.App" />

	  <PackageReference Include="Ardalis.Specification" Version="8.0.0" />

	  <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="NPOI" Version="2.7.2" />
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CliCloud.Domain\CliCloud.Domain.csproj" />
  </ItemGroup>

</Project>
