// <auto-generated />
using System;
using CliCloud.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CliCloud.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260126104926_SecondCreate")]
    partial class SecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CliCloud.Domain.Entities.Documentos.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("CondicaoPagamento")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Data")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataSistemaRegisto")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DescontoCliente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Emitido")
                        .HasColumnType("int");

                    b.Property<int?>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("Exportado")
                        .HasColumnType("bit");

                    b.Property<Guid?>("FuncionarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GlobalHash")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsentoIva")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Liquidado")
                        .HasColumnType("bit");

                    b.Property<string>("LocalidadeCliente")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("MoradaCliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeCliente")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("NumVias")
                        .HasColumnType("int");

                    b.Property<string>("NumeroContribuinteCliente")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("NumeroDocumento")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<Guid?>("OrganismoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Origem")
                        .HasColumnType("int");

                    b.Property<decimal?>("Outros")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Rectificado")
                        .HasColumnType("bit");

                    b.Property<Guid>("TipoDocumentoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TipoModoPagamento")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalDesconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalDocumento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("UtenteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("VersaoChave")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("Estado");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("OrganismoId");

                    b.HasIndex("UtenteId");

                    b.HasIndex("TipoDocumentoId", "NumeroDocumento")
                        .IsUnique();

                    b.ToTable("Documento", "Documentos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Documentos.TipoDocumento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ATCUDData")
                        .HasColumnType("datetime2");

                    b.Property<string>("ATCUDEstado")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<int?>("AtualizaStock")
                        .HasColumnType("int");

                    b.Property<string>("Cae")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CodigoATCUD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("Config")
                        .HasColumnType("int");

                    b.Property<string>("ContabContaConsulta")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContabContaOutros")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContabContaTratamento")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContabDiario")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContabDimensaoCCCredito")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContabDimensaoCCDebito")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContabSeccao")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContabSerieSeccao")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContabTipoConta")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ContabTipoServicoConsulta")
                        .HasColumnType("int");

                    b.Property<int?>("ContabTipoServicoTratamento")
                        .HasColumnType("int");

                    b.Property<string>("ContabValorCCCredito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContabValorCCDebito")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DescarregarTesouraria")
                        .HasColumnType("bit");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("bit");

                    b.Property<int?>("ImprimirEmtodasAsVias")
                        .HasColumnType("int");

                    b.Property<bool>("Inactivo")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("MostraFaturacao")
                        .HasColumnType("bit");

                    b.Property<string>("Natureza")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("NumVias")
                        .HasColumnType("int");

                    b.Property<int?>("NumeroDocumento")
                        .HasColumnType("int");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<int?>("PermiteMovimento")
                        .HasColumnType("int");

                    b.Property<int?>("PocalCodigoServico")
                        .HasColumnType("int");

                    b.Property<int?>("PocalGuiaFatAutartica")
                        .HasColumnType("int");

                    b.Property<int?>("PocalTipoDocPocalCobrado")
                        .HasColumnType("int");

                    b.Property<int?>("PocalTipoDocPocalEmitido")
                        .HasColumnType("int");

                    b.Property<int?>("PocalTipoDocumento")
                        .HasColumnType("int");

                    b.Property<string>("ReportPersonalizado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TemCabecalho")
                        .HasColumnType("int");

                    b.Property<int?>("TipoMovimento")
                        .HasColumnType("int");

                    b.Property<string>("TipoSerie")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Abreviatura")
                        .IsUnique();

                    b.ToTable("TipoDocumento", "Documentos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Especialidades.CategoriaEspecialidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("CategoriaEspecialidade", "Especialidades");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Especialidades.Especialidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Atendimento")
                        .HasColumnType("bit");

                    b.Property<Guid?>("CategoriaEspecialidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Fisioterapia")
                        .HasColumnType("bit");

                    b.Property<bool>("Globalbooking")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaEspecialidadeId");

                    b.ToTable("Especialidade", "Especialidades");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.HorarioMedico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HoraComp")
                        .HasColumnType("bit");

                    b.Property<bool>("HorarioFlexivel")
                        .HasColumnType("bit");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("MedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("MinMarcacao")
                        .HasColumnType("time");

                    b.Property<TimeSpan?>("PrimeiraConsulta")
                        .HasColumnType("time");

                    b.Property<int?>("TipoHorario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MedicoId")
                        .IsUnique();

                    b.ToTable("HorarioMedico", "Medicos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.HorarioMedicoDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("Fim")
                        .HasColumnType("time");

                    b.Property<Guid>("HorarioMedicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeSpan?>("Inicio")
                        .HasColumnType("time");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<string>("Sala")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Vagas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HorarioMedicoId", "DiaSemana", "Periodo")
                        .IsUnique();

                    b.ToTable("HorarioMedicoDia", "Medicos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Tecnicos.HorarioTecnico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HoraComp")
                        .HasColumnType("int");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("MinMarcacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TecnicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("TipoHorario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TecnicoId")
                        .IsUnique();

                    b.ToTable("HorarioTecnico", "Tecnicos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Tecnicos.HorarioTecnicoDia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("int");

                    b.Property<string>("Fim")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HorarioTecnicoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Inicio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NumMarcacoesOutro")
                        .HasColumnType("int");

                    b.Property<int?>("NumMarcacoesPeriodo")
                        .HasColumnType("int");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.Property<string>("Sala")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HorarioTecnicoId", "DiaSemana", "Periodo")
                        .IsUnique();

                    b.ToTable("HorarioTecnicoDia", "Tecnicos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.TipoEntidadeFinanceira.TipoEntidadeFinanceira", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescricaoDominio")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("Dominio")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TipoEntidadeFinanceira", "TipoEntidadeFinanceira");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.CodigoPostal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodigoPostal", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Concelho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DistritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("Concelho", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Distrito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Distrito", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Entidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AndarRua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConcelhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DistritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FreguesiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroContribuinte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPorta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RuaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoEntidade")
                        .HasColumnType("int");

                    b.Property<string>("UrlFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("ConcelhoId");

                    b.HasIndex("DistritoId");

                    b.HasIndex("FreguesiaId");

                    b.HasIndex("PaisId");

                    b.HasIndex("RuaId");

                    b.ToTable("Entidade", "Utility");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.EntidadeContacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadeContactoTipoId")
                        .HasColumnType("int");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Indicativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadeId");

                    b.ToTable("EntidadeContacto", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Freguesia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcelhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConcelhoId");

                    b.ToTable("Freguesia", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefixo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pais", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Rua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FreguesiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("FreguesiaId");

                    b.ToTable("Rua", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Bancos.Banco", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.Entidade");

                    b.ToTable("Banco", "Bancos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.CentroSaude.CentroSaude", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.Entidade");

                    b.Property<string>("CodigoLocalCS")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CentroSaude", "CentroSaude");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Fornecedores.Fornecedor", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.Entidade");

                    b.Property<int?>("Aprovado")
                        .HasColumnType("int");

                    b.Property<int?>("CondicaoPagamento")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DataAprovacao")
                        .HasColumnType("date");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("DiasEfectiEntrega")
                        .HasColumnType("int");

                    b.Property<int?>("DiasPrevEntrega")
                        .HasColumnType("int");

                    b.Property<string>("EnderecoWeb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("InstituicaoFinanceiraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Moeda")
                        .HasColumnType("int");

                    b.Property<string>("NumeroConta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroNib")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Origem")
                        .HasColumnType("int");

                    b.Property<decimal?>("Plafond")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TipoFornecedor")
                        .HasColumnType("int");

                    b.Property<int?>("TipoModoPagamento")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalDebito")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("Fornecedor", "Fornecedores");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Organismos.Organismo", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.Entidade");

                    b.Property<bool>("ADM")
                        .HasColumnType("bit");

                    b.Property<string>("Abreviatura")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("AdmissaoCC")
                        .HasColumnType("int");

                    b.Property<bool>("AlterarPrecoTratamento")
                        .HasColumnType("bit");

                    b.Property<string>("Apolice")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("ApresentarCredenciaisPrimeiraConsulta")
                        .HasColumnType("bit");

                    b.Property<bool>("ApresentarCredenciaisPrimeiraSessaoTratamento")
                        .HasColumnType("bit");

                    b.Property<string>("Ars")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("AssinarPagaDocumento")
                        .HasColumnType("int");

                    b.Property<decimal?>("Avenca")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("BancoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Bloqueio")
                        .HasColumnType("int");

                    b.Property<string>("CServicoFaturaResumo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Categoria")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CodigoClinica")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("CodigoFaturacao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CodigoRegiaoAtestadoCC")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoULSNova")
                        .HasColumnType("int");

                    b.Property<int?>("CondicaoPagamento")
                        .HasColumnType("int");

                    b.Property<string>("ContabContaFA")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContabContaFR")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ContabTipoContaFA")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContabTipoContaFR")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("ContabilizarFaltas")
                        .HasColumnType("bit");

                    b.Property<string>("Contacto")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateOnly?>("DataFimContrato")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicioContrato")
                        .HasColumnType("date");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DescontoUtente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DesignaTratamentos")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("DiscriminaServicos")
                        .HasColumnType("bit");

                    b.Property<int?>("Faltas")
                        .HasColumnType("int");

                    b.Property<int?>("FaturaCredencial")
                        .HasColumnType("int");

                    b.Property<int>("FaturarPorDatas")
                        .HasColumnType("int");

                    b.Property<int?>("FiltroFaturacao")
                        .HasColumnType("int");

                    b.Property<string>("FraseADM")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Globalbooking")
                        .HasColumnType("bit");

                    b.Property<bool>("LimitarConsultas")
                        .HasColumnType("bit");

                    b.Property<int>("Nacional")
                        .HasColumnType("int");

                    b.Property<string>("NomeComercial")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("NumeroConsultas")
                        .HasColumnType("int");

                    b.Property<string>("NumeroIdentificacaoBancaria")
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<int?>("NumeroPagamentos")
                        .HasColumnType("int");

                    b.Property<int?>("PrazoPagamento")
                        .HasColumnType("int");

                    b.Property<string>("Regiao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("SADGNR")
                        .HasColumnType("bit");

                    b.Property<bool>("SADPSP")
                        .HasColumnType("bit");

                    b.Property<string>("Subregiao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("TRUST")
                        .HasColumnType("bit");

                    b.Property<int?>("TipoModoPagamento")
                        .HasColumnType("int");

                    b.Property<int?>("TratamentoCred")
                        .HasColumnType("int");

                    b.HasIndex("BancoId");

                    b.ToTable("Organismo", "Organismos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.EntidadePessoa", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.Entidade");

                    b.Property<string>("Arquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carteira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DataEmissaoCartaoIdentificacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataValidadeCartaoIdentificacao")
                        .HasColumnType("date");

                    b.Property<int?>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUtilizador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCartaoIdentificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacaoBancaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("UrlFotoAssinatura")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EntidadePessoa", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Funcionarios.Funcionario", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.EntidadePessoa");

                    b.ToTable("Funcionario", "Funcionarios");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.Medico", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.EntidadePessoa");

                    b.Property<int>("CartaoCidadaoMedico")
                        .HasColumnType("int");

                    b.Property<bool>("ComunicacaoNif")
                        .HasColumnType("bit");

                    b.Property<bool?>("ComunicacaoNifAdse")
                        .HasColumnType("bit");

                    b.Property<bool>("Director")
                        .HasColumnType("bit");

                    b.Property<Guid?>("EspecialidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Globalbooking")
                        .HasColumnType("bit");

                    b.Property<string>("GrupoFuncional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("IdUtilizador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Letra")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginPRVR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Margem")
                        .HasColumnType("float");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("Medico", "Medicos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.MedicoExterno", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.EntidadePessoa");

                    b.ToTable("MedicoExterno", "Medicos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Tecnicos.Tecnico", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.EntidadePessoa");

                    b.Property<Guid?>("EspecialidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("IdUtilizador")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("Margem")
                        .HasColumnType("float");

                    b.HasIndex("EspecialidadeId");

                    b.ToTable("Tecnico", "Tecnicos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utentes.Utente", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.EntidadePessoa");

                    b.Property<string>("Aviso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CCDataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CCValidado")
                        .HasColumnType("int");

                    b.Property<bool>("Cronico")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataConsentimentoMark")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConsentimentoRgpd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRevogacaoMark")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRevogacaoRgpd")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataValidadeCU")
                        .HasColumnType("date");

                    b.Property<bool>("Desistencia")
                        .HasColumnType("bit");

                    b.Property<int?>("GrupoSanguineo")
                        .HasColumnType("int");

                    b.Property<int>("MarkConsentimento")
                        .HasColumnType("int");

                    b.Property<bool>("MarkTratamentoDados")
                        .HasColumnType("bit");

                    b.Property<bool>("Migrante")
                        .HasColumnType("bit");

                    b.Property<string>("NDocMigrante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSegurancaSocial")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumeroUtente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RgpdConsentimento")
                        .HasColumnType("int");

                    b.Property<int>("TipoConsulta")
                        .HasColumnType("int");

                    b.Property<int?>("TipoTaxaModeradora")
                        .HasColumnType("int");

                    b.HasIndex("NumeroSegurancaSocial");

                    b.HasIndex("NumeroUtente");

                    b.ToTable("Utente", "Utentes");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Documentos.Documento", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Funcionarios.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CliCloud.Domain.Entities.Organismos.Organismo", "Organismo")
                        .WithMany()
                        .HasForeignKey("OrganismoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CliCloud.Domain.Entities.Documentos.TipoDocumento", "TipoDocumento")
                        .WithMany()
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CliCloud.Domain.Entities.Utentes.Utente", "Utente")
                        .WithMany()
                        .HasForeignKey("UtenteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Funcionario");

                    b.Navigation("Organismo");

                    b.Navigation("TipoDocumento");

                    b.Navigation("Utente");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Especialidades.Especialidade", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Especialidades.CategoriaEspecialidade", "CategoriaEspecialidade")
                        .WithMany("Especialidades")
                        .HasForeignKey("CategoriaEspecialidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CategoriaEspecialidade");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.HorarioMedico", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Medicos.Medico", "Medico")
                        .WithOne("Horario")
                        .HasForeignKey("CliCloud.Domain.Entities.Medicos.HorarioMedico", "MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.HorarioMedicoDia", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Medicos.HorarioMedico", "HorarioMedico")
                        .WithMany("Horarios")
                        .HasForeignKey("HorarioMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HorarioMedico");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Tecnicos.HorarioTecnico", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Tecnicos.Tecnico", "Tecnico")
                        .WithOne("Horario")
                        .HasForeignKey("CliCloud.Domain.Entities.Tecnicos.HorarioTecnico", "TecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Tecnicos.HorarioTecnicoDia", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Tecnicos.HorarioTecnico", "HorarioTecnico")
                        .WithMany("Horarios")
                        .HasForeignKey("HorarioTecnicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HorarioTecnico");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Concelho", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Distrito", "Distrito")
                        .WithMany("Concelhos")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Distrito", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Pais", "Pais")
                        .WithMany("Distritos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Entidade", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Concelho", "Concelho")
                        .WithMany()
                        .HasForeignKey("ConcelhoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Freguesia", "Freguesia")
                        .WithMany()
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Rua", "Rua")
                        .WithMany("Entidades")
                        .HasForeignKey("RuaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CodigoPostal");

                    b.Navigation("Concelho");

                    b.Navigation("Distrito");

                    b.Navigation("Freguesia");

                    b.Navigation("Pais");

                    b.Navigation("Rua");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.EntidadeContacto", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Entidade", "Entidade")
                        .WithMany("EntidadeContactos")
                        .HasForeignKey("EntidadeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entidade");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Freguesia", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Concelho", "Concelho")
                        .WithMany("Freguesias")
                        .HasForeignKey("ConcelhoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Concelho");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Rua", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.CodigoPostal", "CodigoPostal")
                        .WithMany("Ruas")
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CliCloud.Domain.Entities.Utility.Freguesia", "Freguesia")
                        .WithMany("Ruas")
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Freguesia");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Bancos.Banco", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Entidade", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Bancos.Banco", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.CentroSaude.CentroSaude", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Entidade", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.CentroSaude.CentroSaude", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Fornecedores.Fornecedor", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Entidade", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Fornecedores.Fornecedor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Organismos.Organismo", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Bancos.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Entidade", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Organismos.Organismo", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Banco");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.EntidadePessoa", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Entidade", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Utility.EntidadePessoa", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Funcionarios.Funcionario", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.EntidadePessoa", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Funcionarios.Funcionario", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.Medico", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Especialidades.Especialidade", "Especialidade")
                        .WithMany()
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CliCloud.Domain.Entities.Utility.EntidadePessoa", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Medicos.Medico", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.MedicoExterno", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.EntidadePessoa", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Medicos.MedicoExterno", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Tecnicos.Tecnico", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Especialidades.Especialidade", "Especialidade")
                        .WithMany()
                        .HasForeignKey("EspecialidadeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CliCloud.Domain.Entities.Utility.EntidadePessoa", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Tecnicos.Tecnico", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidade");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utentes.Utente", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.EntidadePessoa", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Utentes.Utente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Especialidades.CategoriaEspecialidade", b =>
                {
                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.HorarioMedico", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Tecnicos.HorarioTecnico", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.CodigoPostal", b =>
                {
                    b.Navigation("Ruas");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Concelho", b =>
                {
                    b.Navigation("Freguesias");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Distrito", b =>
                {
                    b.Navigation("Concelhos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Entidade", b =>
                {
                    b.Navigation("EntidadeContactos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Freguesia", b =>
                {
                    b.Navigation("Ruas");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Pais", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Rua", b =>
                {
                    b.Navigation("Entidades");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Medicos.Medico", b =>
                {
                    b.Navigation("Horario");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Tecnicos.Tecnico", b =>
                {
                    b.Navigation("Horario");
                });
#pragma warning restore 612, 618
        }
    }
}
