// <auto-generated />
using System;
using CliCloud.Infrastructure.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CliCloud.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260122143908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.CodigoPostal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Localidade")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CodigoPostal", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Concelho", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DistritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistritoId");

                    b.ToTable("Concelho", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Distrito", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("Distrito", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Entidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AndarRua")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ConcelhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DistritoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FreguesiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroContribuinte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroPorta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacoes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PaisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RuaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TipoEntidade")
                        .HasColumnType("int");

                    b.Property<string>("UrlFoto")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("ConcelhoId");

                    b.HasIndex("DistritoId");

                    b.HasIndex("FreguesiaId");

                    b.HasIndex("PaisId");

                    b.HasIndex("RuaId");

                    b.ToTable("Entidade", "Utility");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.EntidadeContacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntidadeContactoTipoId")
                        .HasColumnType("int");

                    b.Property<Guid>("EntidadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Indicativo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Principal")
                        .HasColumnType("bit");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntidadeId");

                    b.ToTable("EntidadeContacto", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Freguesia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConcelhoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConcelhoId");

                    b.ToTable("Freguesia", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prefixo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pais", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Rua", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CodigoPostalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FreguesiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoPostalId");

                    b.HasIndex("FreguesiaId");

                    b.ToTable("Rua", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.EntidadePessoa", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.Entidade");

                    b.Property<string>("Arquivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Carteira")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DataEmissaoCartaoIdentificacao")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataValidadeCartaoIdentificacao")
                        .HasColumnType("date");

                    b.Property<int?>("EstadoCivil")
                        .HasColumnType("int");

                    b.Property<string>("GrupoFuncional")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nacionalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naturalidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUtilizador")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroCartaoIdentificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacaoBancaria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RetencaoImposto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Sexo")
                        .HasColumnType("int");

                    b.Property<string>("UrlFotoAssinatura")
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("EntidadePessoa", "Utility");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utentes.Utente", b =>
                {
                    b.HasBaseType("CliCloud.Domain.Entities.Utility.EntidadePessoa");

                    b.Property<string>("Aviso")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CCDataValidacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CCValidado")
                        .HasColumnType("int");

                    b.Property<bool>("Cronico")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataConsentimentoMark")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataConsentimentoRgpd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRegisto")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRevogacaoMark")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataRevogacaoRgpd")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DataValidadeCU")
                        .HasColumnType("date");

                    b.Property<bool>("Desistencia")
                        .HasColumnType("bit");

                    b.Property<int?>("GrupoSanguineo")
                        .HasColumnType("int");

                    b.Property<int>("MarkConsentimento")
                        .HasColumnType("int");

                    b.Property<bool>("MarkTratamentoDados")
                        .HasColumnType("bit");

                    b.Property<bool>("Migrante")
                        .HasColumnType("bit");

                    b.Property<string>("NDocMigrante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeMae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomePai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroSegurancaSocial")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NumeroUtente")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RgpdConsentimento")
                        .HasColumnType("int");

                    b.Property<int>("TipoConsulta")
                        .HasColumnType("int");

                    b.Property<int?>("TipoTaxaModeradora")
                        .HasColumnType("int");

                    b.HasIndex("NumeroSegurancaSocial");

                    b.HasIndex("NumeroUtente");

                    b.ToTable("Utente", "Utentes");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Concelho", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Distrito", "Distrito")
                        .WithMany("Concelhos")
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Distrito", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Pais", "Pais")
                        .WithMany("Distritos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Entidade", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.CodigoPostal", "CodigoPostal")
                        .WithMany()
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Concelho", "Concelho")
                        .WithMany()
                        .HasForeignKey("ConcelhoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Distrito", "Distrito")
                        .WithMany()
                        .HasForeignKey("DistritoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Freguesia", "Freguesia")
                        .WithMany()
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Pais", "Pais")
                        .WithMany()
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("CliCloud.Domain.Entities.Utility.Rua", "Rua")
                        .WithMany("Entidades")
                        .HasForeignKey("RuaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CodigoPostal");

                    b.Navigation("Concelho");

                    b.Navigation("Distrito");

                    b.Navigation("Freguesia");

                    b.Navigation("Pais");

                    b.Navigation("Rua");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.EntidadeContacto", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Entidade", "Entidade")
                        .WithMany("EntidadeContactos")
                        .HasForeignKey("EntidadeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entidade");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Freguesia", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Concelho", "Concelho")
                        .WithMany("Freguesias")
                        .HasForeignKey("ConcelhoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Concelho");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Rua", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.CodigoPostal", "CodigoPostal")
                        .WithMany("Ruas")
                        .HasForeignKey("CodigoPostalId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CliCloud.Domain.Entities.Utility.Freguesia", "Freguesia")
                        .WithMany("Ruas")
                        .HasForeignKey("FreguesiaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CodigoPostal");

                    b.Navigation("Freguesia");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.EntidadePessoa", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.Entidade", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Utility.EntidadePessoa", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utentes.Utente", b =>
                {
                    b.HasOne("CliCloud.Domain.Entities.Utility.EntidadePessoa", null)
                        .WithOne()
                        .HasForeignKey("CliCloud.Domain.Entities.Utentes.Utente", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.CodigoPostal", b =>
                {
                    b.Navigation("Ruas");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Concelho", b =>
                {
                    b.Navigation("Freguesias");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Distrito", b =>
                {
                    b.Navigation("Concelhos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Entidade", b =>
                {
                    b.Navigation("EntidadeContactos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Freguesia", b =>
                {
                    b.Navigation("Ruas");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Pais", b =>
                {
                    b.Navigation("Distritos");
                });

            modelBuilder.Entity("CliCloud.Domain.Entities.Utility.Rua", b =>
                {
                    b.Navigation("Entidades");
                });
#pragma warning restore 612, 618
        }
    }
}
